"""Added disabled to UserDB

Revision ID: c759c39a0667
Revises: 4dc980fb850e
Create Date: 2026-07-21 10:06:41.025604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c759c39a0667'
down_revision: Union[str, Sequence[str], None] = '4dc980fb850e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdb', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdb', 'disabled')
    # ### end Alembic commands ###
