"""added user_role to UserDB

Revision ID: ee0c0a6218a2
Revises: c759c39a0667
Create Date: 2026-07-22 21:17:25.777370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'ee0c0a6218a2'
down_revision: Union[str, Sequence[str], None] = 'c759c39a0667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdb', sa.Column('user_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdb', 'user_role')
    # ### end Alembic commands ###
